### ISSUE TITLE
Linking to c++

### ISSUE THREAD

**Issue by winstonschen** [jkrukowski/UseSwiftFaiss#1]
Thanks so much for this project! I'm very excited about on-device AI. This might sound like dumb question:
I added SwiftFaiss via SPM. But getting a lot of "undefined symbols". They look like c++ std such as "std::__1::basic_string<char". I added libc++.tbd but it does not resolve the issue. I also tried adding -lc++ and -lstdc++ to other ldflags. 
What am I doing wrong?

**Comment by jkrukowski** [comment]
@winstonschen I pushed some changes, you can find Xcode demo project there, let me know if it works for you

**Comment by winstonschen** [comment]
Thanks! The issue is that when you add the package to a project, two packages are added to the target: "SwiftFaiss" and "swift-faiss". Once I removed the second one, it works.
